# Generated by Django 2.1.4 on 2018-12-26 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checka', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='shop',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AlterField(
            model_name='check',
            name='total_amount',
            field=models.FloatField(default=0.0),
        ),
    ]
